name = "JobSchedulers"
uuid = "eeff360b-c02d-44d3-ab26-4013c616a17e"
authors = ["Jiacheng Chuan <jiacheng_chuan@outlook.com>"]
version = "0.11.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pipelines = "ef544631-5c6f-4e9b-994c-12e7a4cd724c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Terming = "5a1048b7-9ca6-4e8a-8e2e-1f932e78ac4e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataStructures = "0.18"
Distributions = "0.25.112"
JLD2 = "0.4, 0.5"
JSON = "0.21"
Pipelines = "0.9, 0.10, 0.11, 1"
PrecompileTools = "1"
PrettyTables = "0.12, 2"
Reexport = "^1"
Revise = "3"
StatsBase = "0.34.3"
Term = "^2"
Terming = "^0.2.6"
julia = "^1.8"
